# -*- coding: utf-8 -*-
"""James_Tampanga_Web_Scrapping.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14Kpi-6cr119jJBViFed_wxNRpwNCWNwp

#Toronto Daycare Web Scrapper
###By - James Tampanga
"""

import requests
from bs4 import BeautifulSoup
import pandas as pd
import time
import string
import re

BASE_AZ_URL = "https://www.toronto.ca/data/children/dmc/a2z/a2z{letter}.html"
BASE_DETAIL_URL = "https://www.toronto.ca/data/children/dmc/webreg/{page}"

records = []
daycare_links = []

#Looping through all A-Z pages to collect daycare names and detail links
for letter in string.ascii_lowercase:
    url = BASE_AZ_URL.format(letter=letter)
    print(f"Scraping index: {url}")

    try:
        response = requests.get(url, timeout=15)
        response.raise_for_status()
        soup = BeautifulSoup(response.text, "html.parser")

        rows = soup.find_all("tr")
        for row in rows:
            td = row.find("td")
            if td:
                a_tag = td.find("a")
                if a_tag:
                    name = a_tag.get_text(strip=True)
                    href = a_tag.get("href", "")
                    page = href.split("/")[-1]
                    detail_url = BASE_DETAIL_URL.format(page=page)
                    daycare_links.append((name, detail_url))

    except requests.exceptions.RequestException as e:
        print(f"  Error: {e}")

    print(f"  Sleeping 1 second...")
    time.sleep(1)

print(f"\nTotal daycares found: {len(daycare_links)}")

# Getting address and contact info
for i, (name, url) in enumerate(daycare_links):
    print(f"[{i+1}/{len(daycare_links)}] Fetching: {name}")

    address = ""
    contact = ""

    try:
        response = requests.get(url, timeout=15)
        response.raise_for_status()
        soup = BeautifulSoup(response.text, "html.parser")

        # Address is in a <p>
        for p in soup.find_all("p"):
            text = p.get_text(strip=True)
            if any(word in text for word in ["Ave", "St", "Rd", "Dr", "Blvd", "Lane", "Cres", "Court", "Way"]):
                address = " ".join(text.split())
                break

        # Contact is in a <li> tag
        for li in soup.find_all("li"):
            text = li.get_text(strip=True)
            if "Phone:" in text:
                contact = " ".join(text.split())
                break

    except requests.exceptions.RequestException as e:
        print(f"  Error: {e}")

    records.append({
        "Name": name,
        "Address": address,
        "Contact": contact
    })

    print(f"  Sleeping 1 second...")
    time.sleep(1)

# Saving to CSV
df = pd.DataFrame(records, columns=["Name", "Address", "Contact"])
df.drop_duplicates(inplace=True)
df.reset_index(drop=True, inplace=True)

print(f"\nDone! Total records: {len(df)}")
print(df.head())

df.to_csv("results.csv", index=False)
print("Saved to results.csv")

#Cleaning result.csv
import pandas as pd

def clean_text(text):
    if not text:
        return text
    return str(text).replace("\xa0", " ").replace("Â", "").strip()

df = pd.read_csv("results.csv")
df["Name"] = df["Name"].apply(clean_text)
df["Address"] = df["Address"].apply(clean_text)
df["Contact"] = df["Contact"].apply(clean_text)

df.to_csv("results.csv", index=False)
print("Done! CSV cleaned and saved.")